### ISSUE TITLE
Moana failed to download, log file bad

### ISSUE THREAD

**Issue by GMaynard1** [LowellInstruments/ddh#4]
The F/V Alison Ann reported hauling their Moana probe on 8/18 around 0700-0730 eastern time. The logfile for 8/18 is mislabeled (starts on 8/15) and incomplete (only covers from 0520-0655). No error downloading the probe is recorded, but the captain says his deckbox was powered on and he never saw any indication that it connected. This may be related to how long he gives it to power up before it tries to download.

[dds_20230815084857.log](https://github.com/LowellInstruments/ddh/files/12396579/dds_20230815084857.log)
[dds_20230815172502.log](https://github.com/LowellInstruments/ddh/files/12396580/dds_20230815172502.log)

**Comment by kazola** [comment]
Hi,
We clarified this on the phone but just for the record, we will also put it here.

I am going to try to explain this with simpler numbers. Just imagine the DDH is powered down on day 2 and 3:00am.
Then, it is powered on five days later, that is day 7, at let's say 5pm.
The log engine is the first thing it starts on a DDH because it has to take care of recording events.
The Rpi / DDH has no real time clock. 
When the DDH first starts, the log engine still thinks is day 2. Then GPS sync cames in and jumps to day 7. So in the same log file, we have 2 days. The DDH clearly indicates this jump in the log file.

We could reverse this, but then we would lose some logs while booting until the GPS sync. We will have to think about if we want to change this or we leave it like this with the banner indicating the change, which I agree is not great but at least it is more detailed.
